spring:
  cassandra:
    keyspace-name: delivery_ks
    username: cassandra
    password: cassandra
    #schema-action: create_if_not_exists
    local-datacenter: dc1
    contact-points: localhost:9042
springdoc:
  use-management-port: true

management:
  endpoints:
    web:
      exposure:
        include: health, openapi, swagger-ui
  server:
    port: 9090